"""16x16 pixel icons for the feature cards, drawn in the theme's icon style (light tile, dark outline)."""
from lib import *

K = (24, 26, 30)       # outline
P = {
    "k": K, "w": WHITE, "i": INK, "g": INK2, "d": INK3, "b": BLUE, "B": BLUE_DK, "l": BLUE_LT,
    "r": RED, "R": RED_DK, "G": GREEN, "y": YELLOW, "o": (240, 140, 50), "t": TEAL, "T": TEAL_HI,
    "s": (190, 196, 204), "z": (120, 160, 90), "Z": (70, 110, 60), "p": (170, 110, 220), "n": (120, 80, 50),
}

ICONS16 = {
    "3x": [
        "kkkkkkkkkkkkkkkk",
        "kwwwwwwwkwwwwwwk",
        "kwwwwwwwkwwwwwbk",
        "kwwwwwwwkwwwwbbk",
        "kwwwwwwwkwwwwbbk",
        "kwwwwbbbkwwwbbbk",
        "kwwwwbbbkwwbbbbk",
        "kwwwwbbbkwwbbbbk",
        "kwwwwbbbkwbbbbbk",
        "kwbbbbbbkwbbbbbk",
        "kwbbbbbbkbbbbbbk",
        "kwbbbbbbkbbbbbbk",
        "kwbbbbbbkbbbbbbk",
        "kkkkkkkkkkkkkkkk",
        "................",
        "................",
    ],
    "bank": [
        "....kkkkkkkk....",
        "..kkrrrrrrrrkk..",
        ".krrrrrrrrrrrrk.",
        ".krrwrrrrrrrrrk.",
        "krrwrrrrrrrrrrrk",
        "krrrrrrkkrrrrrrk",
        "krrrrrkwwkrrrrrk",
        "kkkkkkkwwkkkkkkk",
        "kwwwwwkwwkwwwwwk",
        "kwwwwwwkkwwwwwwk",
        "kwwwwwwwwwwwwwsk",
        ".kwwwwwwwwwwwsk.",
        ".kswwwwwwwwwssk.",
        "..kkssssssssk...",
        "....kkkkkkkk....",
        "................",
    ],
    "zombie": [
        "....kkkkkkk.....",
        "...kzzzzzzzk....",
        "..kzzZzzzzzzk...",
        "..kzzzzzzzZzk...",
        "..kzkkzzzkkzk...",
        "..kzkrzzzkrzk...",
        "..kzzzzZzzzzk...",
        "..kzzzzzzzzzk...",
        "...kzkwkwkzk....",
        "...kzzzzzzzk....",
        "....kkzzzkk.....",
        "...kRRkkkRRk....",
        "..kRRRRRRRRRk...",
        ".kRRkRRRRRkRRk..",
        ".kzzkRRRRRkzzk..",
        "..kk.kkkkk.kk...",
    ],
    "lifebuoy": [
        ".....kkkkkk.....",
        "...kkrrwwrrkk...",
        "..krrrrwwrrrrk..",
        ".krrrkkkkkkrrrk.",
        ".krrk......krrk.",
        "kwwk........kwwk",
        "kwwk........kwwk",
        "kwwk........kwwk",
        "kwwk........kwwk",
        "kwwk........kwwk",
        ".krrk......krrk.",
        ".krrrkkkkkkrrrk.",
        "..krrrrwwrrrrk..",
        "...kkrrwwrrkk...",
        ".....kkkkkk.....",
        "................",
    ],
    "menu": [
        "kkkkkkkkkkkkkkkk",
        "ktttttttttttttk.",
        "ktkkkkkkkkkkktk.",
        "ktkbbbbbbbbbktk.",
        "ktkbwwwwwwwbktk.",
        "ktkbbbbbbbbbktk.",
        "ktkkkkkkkkkkktk.",
        "ktkiiiiiiiiiktk.",
        "ktkkkkkkkkkkktk.",
        "ktkiiiiiiiiiktk.",
        "ktkkkkkkkkkkktk.",
        "ktkiiiiiiiiiktk.",
        "ktkkkkkkkkkkktk.",
        "ktttttttttttttk.",
        "kkkkkkkkkkkkkkk.",
        "................",
    ],
    "clock": [
        ".....kkkkkk.....",
        "...kkwwwwwwkk...",
        "..kwwwwkwwwwwk..",
        ".kwwwwwkwwwwwwk.",
        ".kwwwwwkwwwwwwk.",
        "kwwwwwwkwwwwwwwk",
        "kwwwwwwkwwwwwwwk",
        "kkwwwwwkkkkkwwkk",
        "kwwwwwwwwwwwwwwk",
        "kwwwwwwwwwwwwwwk",
        ".kwwwwwwwwwwwwk.",
        ".kwwwwwwwwwwwwk.",
        "..kwwwwkwwwwwk..",
        "...kkwwwwwwkk...",
        ".....kkkkkk.....",
        "................",
    ],
    "card": [
        "...kkkkkkkkkk...",
        "...kyykyykyyk...",
        "..kkyykyykyyk...",
        "..kyykyykyykk...",
        "..kkkkkkkkkkkk..",
        "..kssssssssssk..",
        "..ksbbbbbbbbsk..",
        "..ksbwwbbwwbsk..",
        "..ksbwwbbwwbsk..",
        "..ksbbbbbbbbsk..",
        "..ksbbwwwwbbsk..",
        "..ksbbbbbbbbsk..",
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    "gear": [
        "......kkkk......",
        "..kk..kssk..kk..",
        ".kssk.kssk.kssk.",
        ".ksssksssskssk..",
        "..kssssssssssk..",
        "kkkssskkkkssskkk",
        "ksssskwwwwksssk.",
        "ksssskwwwwksssk.",
        "ksssskwwwwksssk.",
        "kkksssk..kssskkk",
        "..ksssskksssk...",
        "..kssssssssssk..",
        ".kssk.kssk.kssk.",
        "..kk..kssk..kk..",
        "......kkkk......",
        "................",
    ],
    "trophy": [
        "..kkkkkkkkkkkk..",
        "kkkyyyyyyyyyykkk",
        "kykyywyyyyyyykyk",
        "kykyywyyyyyyykyk",
        "kykyywyyyyyyykyk",
        ".kkyyyyyyyyyykk.",
        "...kyyyyyyyyk...",
        "....kyyyyyyk....",
        ".....kkyykk.....",
        "......kyyk......",
        "......kyyk......",
        "....kkkkkkkk....",
        "....koooooook...",
        "...kkkkkkkkkkk..",
        "...kooooooooook.",
        "...kkkkkkkkkkkk.",
    ],
    "chip": [
        "..k.k.k.k.k.k...",
        "..k.k.k.k.k.k...",
        "kkkkkkkkkkkkkkk.",
        "kTTTTTTTTTTTTTk.",
        "kTttttttttttTTk.",
        "kTtGGGGGGGGtTTk.",
        "kTtGGGGGGddtTTk.",
        "kTtGGGGGddddtTk.",
        "kTttttttttttTTk.",
        "kTTTTTTTTTTTTTk.",
        "kkkkkkkkkkkkkkk.",
        "..k.k.k.k.k.k...",
        "..k.k.k.k.k.k...",
        "................",
        "................",
        "................",
    ],
    "font": [
        "................",
        "kkkkk...kkkkk...",
        "kwwwk...kwwwk...",
        "kwkkk...kkkwk...",
        "kwwwk...kwwwk...",
        "kkkwk...kwkkk...",
        "kwwwk...kwwwk...",
        "kkkkk...kkkkk...",
        "................",
        "kkkkk...kkkkk...",
        "kwwkk...kwwwk...",
        "kwkwk...kwkkk...",
        "kwwkk...kwkwk...",
        "kwkwk...kwkwk...",
        "kwwkk...kwwwk...",
        "kkkkk...kkkkk...",
    ],
    "heart": [
        "................",
        "..kkkk....kkkk..",
        ".krrrrk..krrrrk.",
        "krrwwrrkkrrrrrrk",
        "krwwrrrrrrrrrrrk",
        "krwrrrrrrrrrrrrk",
        "krrrrrrrrrrrrrRk",
        ".krrrrrrrrrrrRk.",
        "..krrrrrrrrrRk..",
        "...krrrrrrrRk...",
        "....krrrrrRk....",
        ".....krrrRk.....",
        "......krRk......",
        ".......kk.......",
        "................",
        "................",
    ],
    "discord": [
        "................",
        "..kkkkkkkkkkkk..",
        ".kppppppppppppk.",
        "kppppppppppppppk",
        "kppwwwwwwwwwwppk",
        "kppppppppppppppk",
        "kppwwwwwwwwppppk",
        "kppppppppppppppk",
        "kppwwwwwppppPppk",
        "kppppppppppppppk",
        ".kpppppppppppppk",
        "..kkkkpppkkkkkk.",
        ".....kppk.......",
        ".....kpk........",
        ".....kk.........",
        "................",
    ],
}
P["P"] = (120, 80, 180)
P["3"] = BLUE_DK
P["x"] = BLUE_DK


def icon_tile(a, x, y, name, size=24, k=1, tile=(233, 237, 241), outline=(52, 55, 61)):
    """The theme's icon tile: a light rounded square with a dark outline, the 16x16 icon in the middle."""
    a.rrect(x + 1, y + 1, size, size, fill=BG0, r=3)
    a.rrect(x, y, size, size, fill=tile, outline=outline, r=3)
    off = (size - 16 * k) // 2
    a.sprite(x + off, y + off, ICONS16[name], P, k)


def bang(a, x, y):
    """A little hand-drawn '3x' for the 3x icon (two numerals as sprites)."""
    a.sprite(x, y, ["kkk.k.k", "..k.k.k", ".kk..k.", "..k.k.k", "kkk.k.k"], {"k": BLUE_DK})
