// art.h: sprites from art/*.txt (art_data.c is generated by art/build_art.py), turned into images at start.
#pragma once
#include "gfx.h"

typedef struct { const char *name, *colors; } ArtPalette;    /* colors: "k1b1a20h8a2c2c..." */
typedef struct { const char *name; int w, h; const char *palette; const char *rows[64]; } ArtSprite;
extern const ArtPalette ART_PALETTES[];
extern const int ART_NPALETTES;
extern const ArtSprite ART_SPRITES[];
extern const int ART_NSPRITES;

/* the sprite in its own palette, or recoloured with another palette that uses the same characters
 * (missing characters keep the sprite's own colours). Cached: same name and palette, same image. */
const Img *art(const char *name);
const Img *art_pal(const char *name, const char *palette);
/* a palette made at run time (zombie variants): returns its name */
const char *art_palette_add(const char *name, const char *base, const char *overrides);
int art_exists(const char *name);
uint32_t art_color(const char *palette, char ch);
