#!/usr/bin/env python3
"""build_art.py: the game's pixel art, from text to C.

Every sprite is drawn as text in art/*.txt, one character per pixel:

    palette survivor              # name, then "char rrggbb" lines; '.' is always transparent
      k 1b1a20
    end
    sprite player_down_0 16x20 survivor
    ......kkkk......
    ...
    end

    sprite zombie_down_0 16x20 zombie   # palette names are defaults: the game recolours sprites with
                                        # other palettes that use the same characters (zombie variants)

This writes src/art_data.c (the rows as strings, so the C build needs no Python) and, with --preview, a zoomed
sheet of every sprite to look at: python3 art/build_art.py --preview /tmp/sheet.png
"""
import glob, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "art_data.c")


def parse(paths):
    pals, sprites, order = {}, {}, []
    for path in paths:
        lines = open(path, encoding="utf-8").read().split("\n")
        i = 0
        while i < len(lines):
            ln = lines[i].strip()
            i += 1
            if not ln or ln.startswith("#"):
                continue
            parts = ln.split()
            if parts[0] == "palette":
                name, cols = parts[1], {}
                base = parts[2] if len(parts) > 2 else None
                if base:
                    cols.update(pals[base])
                while i < len(lines) and lines[i].strip() != "end":
                    t = lines[i].split("#", 1)[0].split(); i += 1
                    if len(t) == 2:
                        if len(t[0]) != 1 or not re.fullmatch(r"[0-9a-fA-F]{6}", t[1]):
                            sys.exit(f"{path}: bad palette line {t}")
                        cols[t[0]] = t[1].lower()
                i += 1
                pals[name] = cols
            elif parts[0] == "sprite":
                name, size, pal = parts[1], parts[2], parts[3]
                w, h = map(int, size.split("x"))
                rows = []
                while i < len(lines) and lines[i].strip() != "end":
                    r = lines[i].rstrip("\n"); i += 1
                    r = r.strip()
                    if r.startswith("#") or not r:
                        continue
                    rows.append(r)
                i += 1
                if len(rows) != h:
                    sys.exit(f"{path}: sprite {name}: {len(rows)} rows, expected {h}")
                for k, r in enumerate(rows):
                    if len(r) != w:
                        sys.exit(f"{path}: sprite {name} row {k}: {len(r)} wide, expected {w}: '{r}'")
                if name in sprites:
                    sys.exit(f"{path}: sprite {name} defined twice")
                sprites[name] = (w, h, pal, rows); order.append(name)
            else:
                sys.exit(f"{path}: unexpected line: {ln}")
    for name in order:
        w, h, pal, rows = sprites[name]
        if pal not in pals:
            sys.exit(f"sprite {name}: unknown palette {pal}")
        used = set("".join(rows)) - {"."}
        missing = used - set(pals[pal])
        if missing:
            sys.exit(f"sprite {name}: characters {sorted(missing)} not in palette {pal}")
    return pals, sprites, order


def write_c(pals, sprites, order):
    o = ["// Generated by art/build_art.py from art/*.txt: edit those, then run python3 art/build_art.py",
         '#include "art.h"', "", "const ArtPalette ART_PALETTES[] = {"]
    for name, cols in pals.items():
        enc = "".join(f"{c}{v}" for c, v in sorted(cols.items()))
        o.append(f'    {{"{name}", "{enc}"}},')
    o.append("};")
    o.append(f"const int ART_NPALETTES = {len(pals)};")
    o.append("")
    o.append("const ArtSprite ART_SPRITES[] = {")
    for name in order:
        w, h, pal, rows = sprites[name]
        o.append(f'    {{"{name}", {w}, {h}, "{pal}", {{')
        for r in rows:
            o.append(f'        "{r}",')
        o.append("    }},")
    o.append("};")
    o.append(f"const int ART_NSPRITES = {len(order)};")
    open(OUT, "w").write("\n".join(o) + "\n")


def preview(pals, sprites, order, path, zoom=4, only=None):
    from PIL import Image, ImageDraw
    names = [n for n in order if not only or any(n.startswith(p) for p in only)]
    cells = []
    for n in names:
        w, h, pal, rows = sprites[n]
        cells.append((n, w, h, pal, rows))
    maxw = 820
    x = y = 8; rowh = 0; placed = []
    for c in cells:
        cw = max(c[1] * zoom, 60) + 8; ch = c[2] * zoom + 14
        if x + cw > maxw:
            x = 8; y += rowh; rowh = 0
        placed.append((x, y, c)); x += cw; rowh = max(rowh, ch)
    H = y + rowh + 8
    im = Image.new("RGB", (maxw, H), (60, 64, 72))
    d = ImageDraw.Draw(im)
    for x, y, (n, w, h, pal, rows) in placed:
        for j in range(h):
            for i in range(w):
                ch = rows[j][i]
                bg = (88, 92, 100) if (i + j) % 2 == 0 else (80, 84, 92)
                col = bg if ch == "." else tuple(int(pals[pal][ch][k:k + 2], 16) for k in (0, 2, 4))
                d.rectangle([x + i * zoom, y + j * zoom, x + i * zoom + zoom - 1, y + j * zoom + zoom - 1], fill=col)
        d.text((x, y + h * zoom + 1), n[:14], fill=(230, 230, 230))
    im.save(path)


if __name__ == "__main__":
    pals, sprites, order = parse(sorted(glob.glob(os.path.join(HERE, "*.txt"))))
    write_c(pals, sprites, order)
    if "--preview" in sys.argv:
        i = sys.argv.index("--preview")
        only = sys.argv[i + 2].split(",") if len(sys.argv) > i + 2 else None
        preview(pals, sprites, order, sys.argv[i + 1], only=only)
    print(f"{len(order)} sprites, {len(pals)} palettes -> src/art_data.c")
